### ISSUE TITLE
Can ES 3.1 match a non-location in one stage to a location in another?

### ISSUE THREAD

**Issue by johnkslang** [KhronosGroup/OpenGL-GLSL#9]
See https://github.com/KhronosGroup/glslang/issues/1172

**Comment by absinthe99** [comment]
ES3.2 
An output variable is considered to match an input variable in the subsequent
shader if:
– the two variables match in name, type, and qualification, and neither has a location qualifier; or
– the two variables are declared with the same location qualifier and match in type and qualification.


ES3.1 
An output variable is considered to match an input variable in the subsequent
shader if:
- the two variables match in name, type, and qualification; or
- the two variables are declared with the same location qualifier and match in type and qualification

**Comment by pdaniell-nv** [comment]
This was something that came up before and we fixed in the OpenGL 4.5 and OpenGL ES 3.2 specifications. In general we don't usually put fixes into older specifications. In this case it was a backward incompatible change and may have invalidated existing OpenGL ES 3.1 implementations. Existing ES 3.1 implementations may be inconsistent in their behavior when there is a mix of location and name matching. If your app follows the ES 3.2 rules, it should work consistently with ES 3.1 and ES 3.2 implementations.

For reference internally, this bug was discussed here:
https://cvs.khronos.org/bugzilla/show_bug.cgi?id=13613
